import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-6 h-dvh flex flex-col`}
      >
        <nav className=" flex bg-slate-100 justify-between mt-4 text-3xl px-4 py-2 rounded-md">
          {/* logo */}
          <div className="flex items-center gap-1">
            <span className="text-2xl">📝</span>
            Assignment
          </div>

          {/* action buttons */}
          <div className="flex gap-4">
            <Link
              href="/login"
              className="bg-slate-700 text-slate-100 py-1 rounded-md px-3 transition-all hover:bg-slate-800"
            >
              Login
            </Link>

            <button className="bg-slate-700 text-slate-100 py-1 rounded-md px-3 transition-all hover:bg-slate-800">
              Logout
            </button>
          </div>
        </nav>
        <main className="flex-1 relative my-2 ">{children}</main>
      </body>
    </html>
  );
}
